#!/bin/sh
# Start the cluster and run N clients sequentially.
# The i-th client (0-indexed) is invoked as: run-client i i i
#
# Usage: ./run-clients <program.stflb> <N> [run-nodes options...]
#   e.g. ./run-clients client_mul.stflb 4 --loss 5 --bandwidth 100

set -e

usage() { echo "Usage: $0 <program.stflb> <N> [--loss <pct>] [--bandwidth <mbit>] [--delay <ms>]" >&2; exit 1; }

PROGRAM="${1:?$(usage)}"; shift
N="${1:?$(usage)}"; shift

DIR="$(cd "$(dirname "$0")" && pwd)"

"$DIR/run-nodes" "$PROGRAM" --n-input-clients "$N" "$@"

sleep 1

i=0
while [ "$i" -lt "$N" ]; do
    "$DIR/run-client" "$i" "$((i+1))" "$i" &
    i=$((i + 1))
    echo "Started client $i"
done
