"""Claims a one-time WebAuthn registration link, verifies the resulting registration
ceremony, and records the credential's server-derived public key.

No API key required on this route (see app.py's `_add_api` - `api_key_required=False`): the
one-time token itself, generated by ./generate-registration-link and known only to whoever
the operator sent it to, is what restricts who can register - not a shared deployment-wide
API key a voter would otherwise need to somehow be given out-of-band too.

Verification is delegated entirely to `py_webauthn` (PyPI package `webauthn`) rather than
hand-rolled: `verify_registration_response` checks the ceremony type, the challenge (against
the value `registration_options.py` generated and stored - see that file for why this two-step
options-then-verify flow is the standard WebAuthn shape, not a one-shot POST), the origin, the
RP ID hash, the user-presence/user-verification flags, and the signature. The public key this
Lambda stores is derived by this Lambda itself from the *verified* attestation object
(`decode_credential_public_key`/`decoded_public_key_to_cryptography`, both public helpers from
`webauthn.helpers`) - never trusted from a client-asserted field - and converted to the exact
65-byte uncompressed SEC1 point (`0x04 || x || y`) this system already stores everywhere else,
so nothing downstream changes: `./materialize-registered-clients` writes it straight into the
`.crt` files admission's `clients` list understands, and StandingClientCatalog::load (StoffelVM's
crates/stoffel-vm-runner/src/standing_control.rs) accepts it directly via `parse_client_identity`.
Kept as a separate operator-run materialize step rather than done here so the operator retains
a manual checkpoint before a voter-submitted key becomes part of the actual deployed roster,
rather than this publicly-reachable, no-API-key-required Lambda writing to deployment
infrastructure directly.
"""
import json
import os
from datetime import datetime, timezone

import boto3
from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurvePublicKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
from webauthn import verify_registration_response
from webauthn.helpers import decode_credential_public_key, decoded_public_key_to_cryptography
from webauthn.helpers.exceptions import InvalidRegistrationResponse
from webauthn.helpers.structs import (
    AuthenticatorAttestationResponse,
    PublicKeyCredentialType,
    RegistrationCredential,
)

dynamodb = boto3.resource("dynamodb")

CLIENT_REGISTRATIONS_TABLE_NAME = os.environ["CLIENT_REGISTRATIONS_TABLE_NAME"]
WEBAUTHN_RP_ID = os.environ["WEBAUTHN_RP_ID"]
WEBAUTHN_ORIGIN = f"https://{WEBAUTHN_RP_ID}"
client_registrations_table = dynamodb.Table(CLIENT_REGISTRATIONS_TABLE_NAME)


def _now():
    return datetime.now(timezone.utc).isoformat()


def _bytes_from_json_array(value):
    if not isinstance(value, list) or not value:
        return None
    try:
        return bytes(value)
    except (TypeError, ValueError):
        return None


def _parse_credential(raw):
    """Builds a `RegistrationCredential` directly from this codebase's own established
    over-the-wire convention (byte fields as JSON arrays of ints, same as every other
    endpoint here) rather than routing through py_webauthn's JSON-string parsing helper
    (which expects the WebAuthn spec's own base64url-string serialization) - avoids any
    ambiguity between the two encodings."""
    if not isinstance(raw, dict):
        return None
    response = raw.get("response")
    if not isinstance(response, dict):
        return None
    raw_id = _bytes_from_json_array(raw.get("rawId"))
    client_data_json = _bytes_from_json_array(response.get("clientDataJSON"))
    attestation_object = _bytes_from_json_array(response.get("attestationObject"))
    if not isinstance(raw.get("id"), str) or raw_id is None or client_data_json is None or attestation_object is None:
        return None
    return RegistrationCredential(
        id=raw["id"],
        raw_id=raw_id,
        response=AuthenticatorAttestationResponse(
            client_data_json=client_data_json,
            attestation_object=attestation_object,
        ),
        type=PublicKeyCredentialType.PUBLIC_KEY,
    )


def handler(event, context):
    try:
        body = json.loads(event.get("body") or "{}")
    except json.JSONDecodeError:
        return _response(400, {"error": "invalid JSON body"})

    token = body.get("token")
    if not token or not isinstance(token, str):
        return _response(400, {"error": "token is required"})

    credential = _parse_credential(body.get("credential"))
    if credential is None:
        return _response(
            400,
            {"error": "credential must include id, rawId, response.clientDataJSON, and "
                       "response.attestationObject - see POST /client-registrations/options"},
        )

    item = client_registrations_table.get_item(Key={"token": token}).get("Item")
    if not item:
        return _response(404, {"error": "this registration link is invalid or has already been used"})
    if item.get("used_at"):
        return _response(409, {"error": "this registration link is invalid or has already been used"})
    stored_challenge = item.get("challenge")
    if not stored_challenge:
        return _response(
            400, {"error": "no challenge on file for this token - call POST /client-registrations/options first"}
        )

    try:
        verified = verify_registration_response(
            credential=credential,
            expected_challenge=bytes(stored_challenge),
            expected_rp_id=WEBAUTHN_RP_ID,
            expected_origin=WEBAUTHN_ORIGIN,
            require_user_verification=True,
        )
    except InvalidRegistrationResponse as error:
        return _response(400, {"error": f"WebAuthn registration did not verify: {error}"})

    public_key = decoded_public_key_to_cryptography(decode_credential_public_key(verified.credential_public_key))
    if not isinstance(public_key, EllipticCurvePublicKey):
        return _response(400, {"error": "expected an EC (P-256) credential"})
    # The exact 65-byte uncompressed SEC1 point (0x04 || x || y) already stored everywhere
    # else in this system - derived here from the verified attestation object, never from
    # anything the client separately asserted.
    public_key_bytes = public_key.public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)

    try:
        item = client_registrations_table.update_item(
            Key={"token": token},
            UpdateExpression="SET credential_id = :cred, public_key = :pub, used_at = :now REMOVE challenge",
            ConditionExpression="attribute_exists(#t) AND attribute_not_exists(used_at)",
            ExpressionAttributeNames={"#t": "token"},
            ExpressionAttributeValues={
                ":cred": verified.credential_id,
                ":pub": public_key_bytes,
                ":now": _now(),
            },
            ReturnValues="ALL_NEW",
        )["Attributes"]
    except dynamodb.meta.client.exceptions.ConditionalCheckFailedException:
        return _response(
            409, {"error": "this registration link is invalid or has already been used"}
        )

    return _response(200, {"client_name": item["client_name"]})


def _response(status, payload):
    return {
        "statusCode": status,
        # Access-Control-Allow-Origin lets a browser page (register.html) call this API with
        # fetch() directly - see submit_execution.py's _response for the full explanation.
        "headers": {"Content-Type": "application/json", "Access-Control-Allow-Origin": "*"},
        "body": json.dumps(payload, default=str),
    }
